"""Red check: each mutation breaks the engine in one known way; its named test must then fail.

  python3 engine/tests/redcheck.py [step]

A mutation whose test still passes means that test cannot see the fault it claims to guard.
"""
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ENGINE = Path(__file__).resolve().parents[1]
ROOT = ENGINE.parent  # experimental/writing-loop: engine/ and hooks/ are copied together, tests import both

# (step, file, old, new, test id). A bare file name is under engine/loop; a path with "/" is under ROOT.
MUTATIONS = [
    ("cov", 'skill:readers/scripts/build-reader-packet.py', '        if t[k] == "\\\\":\n            k += 2\n            continue\n', '',
     'test_readers.ReadersTest.test_alt_text_with_an_escaped_brace_or_a_short_form_and_a_table_spec_do_not_leak_or_swallow'),
    ("cov", 'skill:readers/scripts/build-reader-packet.py', '    t = drop_env_args(t)', '    pass',
     'test_readers.ReadersTest.test_alt_text_with_an_escaped_brace_or_a_short_form_and_a_table_spec_do_not_leak_or_swallow'),
    ("cov", 'coverage.py', '        elif check_id == "notes-lint" and data and all(isinstance(v, list) for v in data.values()):',
     '        elif False:',
     'test_coverage.NeverGreenTest.test_a_notes_lint_result_is_summarised_by_file_not_by_its_first_line'),
    # 检查覆盖与接线（spec 2026-09-21）：每条关键判断拿掉，对应测试必须变红。
    ("cov", 'targets.py', '    if m and cfg.get("transcripts") and _approval_in_transcripts(cfg, m.group(1)):', '    if m:',
     'test_coverage.TargetTest.test_a_card_finalised_by_claude_on_the_authors_word_is_delegated_only_if_that_word_is_on_record'),
    ("cov", 'skill:readers/scripts/build-reader-packet.py', '        PERSONAS.update(personas)', '        pass',
     'test_readers.ReadersTest.test_personas_and_questions_can_come_from_the_workspace'),
    ("cov", 'skill:readers/scripts/build-reader-packet.py', '        text = readable(" ".join(t for t, _, _ in para), bib, unknown)',
     '        text = " ".join(readable(t, bib, unknown) for t, _, _ in para)',
     'test_readers.ReadersTest.test_the_packet_shows_what_the_page_shows_not_the_markup_or_the_alt_text'),
    ("cov", 'skill:readers/scripts/build-reader-packet.py', '    t = drop_command(t, "Description")', '    pass',
     'test_readers.ReadersTest.test_the_packet_shows_what_the_page_shows_not_the_markup_or_the_alt_text'),
    ("cov", 'skill:readers/scripts/build-reader-packet.py', '    t = re.sub(r"\\\\begin\\{[^}]*\\}(?:\\[[^\\]]*\\])*", " ", t)', '    pass',
     'test_readers.ReadersTest.test_the_packet_shows_what_the_page_shows_not_the_markup_or_the_alt_text'),
    ("cov", 'coverage.py', '        inputs[f"?{role}"] = _git(cfg["repo"], "rev-parse", f"{head}:{path}")', '        pass',
     'test_coverage.Grill2Test.test_a_citation_check_reads_the_notes_and_a_run_that_read_none_fails'),
    ("cov", 'coverage.py', ' | set(optional_inputs(check, cfg, head).values()))', ')',
     'test_coverage.Grill2Test.test_a_citation_check_reads_the_notes_and_a_run_that_read_none_fails'),
    ("cov", 'coverage.py', '    if isinstance(data, dict) and data.get("citations_checked") and data.get("notes_sources_indexed") == 0:', '    if False:',
     'test_coverage.Grill2Test.test_a_citation_check_reads_the_notes_and_a_run_that_read_none_fails'),
    ("cov", 'coverage.py', '        if fmt != "latex":\n            # Markdown citations', '        if False:\n            # Markdown citations',
     'test_coverage.Grill2Test.test_a_markdown_citation_check_watches_the_whole_text'),
    ("cov", 'coverage.py', '            "keys": {n: K.get(cfg, n) for n in check.get("config_keys") or []},', '            "keys": {},',
     'test_coverage.GrillTest.test_a_config_key_the_check_reads_makes_it_stale_and_an_unrelated_one_does_not'),
    ("cov", 'coverage.py', '            if fingerprint(cfg, ws) != s.get("fingerprint"):', '            if False:',
     'test_coverage.Grill2Test.test_a_summary_is_not_current_once_a_check_script_or_its_set_of_checks_changes'),
    ("cov", 'coverage.py', '        if {c["id"] for c in K.all_checks(cfg)} - {r.get("id") for r in s["rows"]}:', '        if False:',
     'test_coverage.Grill2Test.test_a_summary_is_not_current_once_a_check_script_or_its_set_of_checks_changes'),
    ("cov", 'coverage.py', '            if q.is_absolute() and q.is_file():', '            if False:',
     'test_coverage.Grill2Test.test_a_project_check_whose_script_lives_outside_the_repository_follows_that_script'),
    ("cov", 'coverage.py', '    except (tarfile.TarError, OSError) as e:', '    except KeyError as e:',
     'test_coverage.Grill2Test.test_a_symlink_out_of_the_repository_fails_one_check_not_the_summary'),
    ("cov", 'coverage.py', '    reason = waivers(ws).get(check["id"])', '    reason = (cfg.get("waive") or {}).get(check["id"])',
     'test_coverage.NeverGreenTest.test_a_waiver_is_shown_with_its_reason'),
    ("cov", 'coverage.py', '    if wv:\n        bits.append("已豁免 "', '    if False:\n        bits.append("已豁免 "',
     'test_coverage.NeverGreenTest.test_a_waiver_is_shown_with_its_reason'),
    ("cov", 'lintel.py', '        out.append({"label": "豁免", "value": str(wv)})', '        pass',
     'test_lintel.CoverageStatTest.test_a_waiver_is_counted_on_the_card'),
    ("cov", 'targets.py', '    if check and "target.venue_corpus.dir" in check["needs"]:', '    if check_id == "fingerprint-venue":',
     'test_coverage.Grill2Test.test_every_check_against_the_venue_corpus_validates_it'),
    ("cov", 'targets.py', '            if any(q == b or str(q).startswith(str(b) + "/") for b in banned):', '            if False:',
     'test_coverage.TargetTest.test_experiments_without_a_disposition_or_past_review_are_listed'),
    ("cov", 'targets.py', '            if not q.exists() or not str(q).startswith(str(r.resolve()) + "/"):', '            if not q.exists():',
     'test_coverage.TargetTest.test_experiments_without_a_disposition_or_past_review_are_listed'),
    ("cov", 'targets.py', '        elif kind == "退役" and len(re.sub(r"[\\s—\\-–:：◌]", "", rest)) < 6:', '        elif False:',
     'test_coverage.TargetTest.test_experiments_without_a_disposition_or_past_review_are_listed'),
    ("cov", 'targets.py', '    text = re.sub(r"(?ms)^```.*?^```", "", text)', '    pass',
     'test_coverage.TargetTest.test_experiments_without_a_disposition_or_past_review_are_listed'),
    ("cov", 'skill:readers/scripts/check-reader-output.py', '    key = json.dumps(_normal(data), sort_keys=True, ensure_ascii=False)', '    key = json.dumps(data, sort_keys=True, ensure_ascii=False)',
     'test_readers.ReadersTest.test_an_output_for_another_packet_or_a_copy_is_not_a_reader'),
    ("cov", 'hooks/loop_hook.py', 's.get("cwd_prefix") and s.get("git_branch") and _under(cwd, s["cwd_prefix"])', 's.get("cwd_prefix") and _under(cwd, s["cwd_prefix"])',
     'test_hooks.PromptTest.test_a_history_source_session_sees_coverage_and_nothing_is_recorded'),
    ("cov", 'coverage.py', '        h.update(json.dumps(check.get("definition"), sort_keys=True, ensure_ascii=False).encode())', '        pass',
     'test_coverage.ProjectCheckTest.test_changing_a_project_checks_command_makes_its_old_result_stale'),
    ("cov", 'hooks/loop_hook.py', '        hws, hcfg = history_ws(payload, regs)\n        if hws is None:\n            return None', '        hws, hcfg = None, None\n        if hws is None:\n            return None',
     'test_hooks.PromptTest.test_a_history_source_session_sees_coverage_and_nothing_is_recorded'),
    ("cov", 'coverage.py', '            if not check.get("auto", True) and not (only and check["id"] in only):\n                continue', '            if False:\n                continue',
     'test_coverage.ProjectCheckTest.test_a_slow_project_check_runs_only_when_named_and_any_change_in_the_tree_makes_it_stale'),
    ("cov", 'coverage.py', '    if kind == "tree":\n        return {"tree":', '    if False:\n        return {"tree":',
     'test_coverage.ProjectCheckTest.test_a_slow_project_check_runs_only_when_named_and_any_change_in_the_tree_makes_it_stale'),
    ("cov", 'coverage.py', 'verdict, summary = ("ok", "通过") if r.returncode == 0 else ("failed",', 'verdict, summary = ("ok", "通过") if True else ("failed",',
     'test_coverage.ProjectCheckTest.test_a_project_check_that_exits_non_zero_is_a_failure'),
    ("cov", 'targets.py', '        if kind == "已晋升" and not _promoted_target_exists(rest, roots, dirs):', '        if False:',
     'test_coverage.TargetTest.test_experiments_without_a_disposition_or_past_review_are_listed'),
    ("cov", 'targets.py', '    head = "\\n".join([ln for ln in text.splitlines() if ln.strip()][:HEAD_LINES])', '    head = text',
     'test_coverage.TargetTest.test_experiments_without_a_disposition_or_past_review_are_listed'),
    ("cov", 'catalogue.py', '    for s in sorted(set(skills) - owners - set(SKILL_ROLES) - set(MODEL_READ)):', '    for s in []:',
     'test_catalogue.WiringTest.test_a_skill_that_checks_nothing_and_says_nothing_is_seen'),
    ("cov", 'catalogue.py', '        for name in sorted(set(not_checks) ^ NOT_CHECKS_ACK):', '        for name in []:',
     'test_catalogue.WiringTest.test_moving_a_check_into_not_checks_alone_is_seen'),
    ("cov", 'skill:audit/scripts/audit-prose-structure.py', '        out = v < vals[0] or v > vals[-1]', '        out = False',
     'test_structure.StructureTest.test_sentences_that_open_with_a_condition_are_outside_a_plain_baseline'),
    ("cov", 'skill:audit/scripts/audit-prose-structure.py', '            "opens_with_sub": sum(1 for s in sents if OPENER.match(s)) / len(sents),', '            "opens_with_sub": 0.0,',
     'test_structure.StructureTest.test_sentences_that_open_with_a_condition_are_outside_a_plain_baseline'),
    ("cov", 'skill:audit/scripts/audit-prose-structure.py', '    if len(rows) < a.min_baseline:', '    if False:',
     'test_structure.StructureTest.test_nothing_to_measure_and_a_thin_baseline_exit_2'),
    ("cov", 'skill:audit/scripts/audit-prose-structure.py', '    if tm is None:\n        die(', '    if tm is None and False:\n        die(',
     'test_structure.StructureTest.test_nothing_to_measure_and_a_thin_baseline_exit_2'),
    ("cov", 'skill:readers/scripts/check-reader-output.py', '    if data.get("packet") != packet.get("packet_id"):', '    if False:',
     'test_readers.ReadersTest.test_an_output_for_another_packet_or_a_copy_is_not_a_reader'),
    ("cov", 'skill:readers/scripts/check-reader-output.py', '        return [f"identical to {seen[key]}"]', '        return []',
     'test_readers.ReadersTest.test_an_output_for_another_packet_or_a_copy_is_not_a_reader'),
    ("cov", 'skill:readers/scripts/tally-readers.py', '    shape = panel_shape(readers, max(a.min_readers, MIN_PANEL))', '    shape = panel_shape(readers, a.min_readers)',
     'test_readers.ReadersTest.test_the_eight_reader_floor_cannot_be_lowered_and_one_judge_is_not_a_judgment'),
    ("cov", 'skill:readers/scripts/tally-readers.py', '            if len(vals) < MIN_JUDGES:\n                continue', '            if False:\n                continue',
     'test_readers.ReadersTest.test_the_eight_reader_floor_cannot_be_lowered_and_one_judge_is_not_a_judgment'),
    ("cov", 'coverage.py', '    got = H._draft_at(cfg, head)', '    got = sorted(n for n in (_git(cfg["repo"], "ls-tree", "-r", "--name-only", head) or "").splitlines() if fnmatch.fnmatch(n, cfg["draft"]["glob"]))',
     'test_coverage.GrillTest.test_a_glob_draft_is_checked_on_the_one_file_the_index_tracks'),
    ("cov", 'coverage.py', '    if kind == "all" or (kind == "cite" and draft_format(cfg) != "latex"):\n        return {f: _git(', '    if False:\n        return {f: _git(',
     'test_coverage.GrillTest.test_text_the_index_does_not_see_still_makes_a_whole_text_check_stale'),
    ("cov", 'coverage.py', '            lines += [f"{f}\\0{ln}" for ln in text.splitlines() if rx.search(ln)]', '            lines += []',
     'test_coverage.GrillTest.test_a_citation_in_an_unindexed_section_makes_a_citation_check_stale'),
    ("cov", 'coverage.py', '    elif old.get("order") != new["order"]:', '    elif False:',
     'test_coverage.GrillTest.test_reordering_paragraphs_makes_a_sections_check_stale'),
    ("cov", 'coverage.py', '    if index_head and index_head != head:', '    if False:',
     'test_coverage.GrillTest.test_an_index_behind_head_and_a_summary_for_an_older_head_are_never_current'),
    ("cov", 'coverage.py', '        if now != s.get("head"):', '        if False:',
     'test_coverage.GrillTest.test_an_index_behind_head_and_a_summary_for_an_older_head_are_never_current'),
    ("cov", 'coverage.py', '    if summary.get("stale_head"):', '    if False:',
     'test_coverage.GrillTest.test_an_index_behind_head_and_a_summary_for_an_older_head_are_never_current'),
    ("cov", 'coverage.py', '    if not ok or (cfg and s.get("workspace") != cfg.get("name", s.get("workspace"))):', '    if False:',
     'test_coverage.GrillTest.test_a_summary_of_another_workspace_or_schema_is_not_trusted'),
    ("cov", 'coverage.py', '        if rec is not None and rec.get("verdict") == "failed":', '        if False:',
     'test_coverage.GrillTest.test_a_waiver_does_not_hide_a_failure_and_the_cell_never_says_all_current_with_one'),
    ("cov", 'coverage.py', '        if not gap and not wv:', '        if True:',
     'test_coverage.GrillTest.test_a_waiver_does_not_hide_a_failure_and_the_cell_never_says_all_current_with_one'),
    ("cov", 'coverage.py', '        files = [p] if (Path(s).is_absolute() or s.startswith("scripts/")) else \\', '        files = [p] if True else \\',
     'test_coverage.GrillTest.test_a_library_beside_the_script_makes_it_stale'),
    ("cov", 'coverage.py', '        rows = sorted(f"{q.relative_to(p)}\\0{file_digest(q)}" for q in p.rglob("*") if q.is_file())', '        rows = sorted(f"{q.relative_to(p)}\\0{q.stat().st_size}" for q in p.rglob("*") if q.is_file())',
     'test_coverage.GrillTest.test_a_same_size_change_in_a_corpus_is_a_different_corpus'),
    ("cov", 'coverage.py', '    if not head:\n        return {**base, "status": FAILED', '    if False:\n        return {**base, "status": FAILED',
     'test_coverage.GrillTest.test_an_unresolvable_ref_is_a_failure'),
    ("cov", 'coverage.py', '    if old.get("config") != new["config"]:', '    if False:',
     'test_coverage.GrillTest.test_a_config_key_the_check_reads_makes_it_stale_and_an_unrelated_one_does_not'),
    ("cov", 'coverage.py', '        out.update({f"also{i}": q for i, q in enumerate(also_checked(cfg))})', '        pass',
     'test_coverage.GrillTest.test_files_submitted_with_the_draft_are_read_and_watched'),
    ("cov", 'lintel.py', '        out.append({"label": "AWT 读不了", "value": str(gap)})', '        pass',
     'test_lintel.CoverageStatTest.test_a_check_the_toolkit_cannot_run_here_is_counted_as_a_gap'),
    ("cov", 'coverage.py', '    if not isinstance(data, dict):\n        # Every catalogued check', '    if False:\n        # Every catalogued check',
     'test_coverage.NeverGreenTest.test_exit_1_without_a_result_is_a_crash_not_a_finding'),
    ("cov", 'catalogue.py', '        for s in sorted(set(skills) - set(documented)):', '        for s in []:',
     'test_catalogue.WiringTest.test_the_invariant_sees_a_skill_nobody_can_find'),
    ("cov", 'coverage.py', 'return [r for r in summary["rows"] if r["status"] == OK and r.get("verdict") == "findings"]', 'return []',
     'test_coverage.ShownTest.test_the_reminder_names_what_is_not_current_and_is_silent_otherwise'),
    ("cov", 'overview.py', '                Path(self.cfg["_ws"]) / "cache" / "coverage" / "summary.json"]', ']',
     'test_overview.TodoTest.test_the_last_todo_row_is_coverage_and_it_refreshes_when_a_check_runs'),
    ("cov", 'overview.py', '    cells.append(V.todo_cell(V.load_summary(ws, full)))', '    pass',
     'test_overview.TodoTest.test_the_last_todo_row_is_coverage_and_it_refreshes_when_a_check_runs'),
    ("cov", 'lintel.py', '        d["stats"] = (list(d["stats"]) + _coverage_stats(coverage))[:8]', '        pass',
     'test_lintel.CoverageStatTest.test_checks_needing_attention_are_counted_and_none_is_quiet'),
    ("cov", 'lintel.py', '        return [{"label": "检查", "value": "没算过", "tone": "orange"}]', '        return [{"label": "检查待办", "value": "0"}]',
     'test_lintel.CoverageStatTest.test_a_workspace_never_computed_says_so_in_orange'),
    ("cov", 'skill:readers/scripts/tally-readers.py', '            c += all(x == "hit" for x in vals)', '            c += any(x == "hit" for x in vals)',
     'test_readers.ReadersTest.test_a_full_panel_is_recorded_as_the_current_reading_until_an_in_scope_edit'),
    ("cov", 'skill:readers/scripts/tally-readers.py', '    if len(readers) < min_readers:', '    if False:',
     'test_readers.ReadersTest.test_fewer_than_eight_readers_is_a_failure_even_with_both_personas_and_models'),
    ("cov", 'skill:readers/scripts/tally-readers.py', '    if shape[0]:\n        verdict, summary = "failed"', '    if False:\n        verdict, summary = "failed"',
     'test_readers.ReadersTest.test_a_small_panel_is_recorded_as_a_failure_not_a_reading'),
    ("cov", 'skill:readers/scripts/tally-readers.py', '    if not readers:\n        die(', '    if False:\n        die(',
     'test_readers.ReadersTest.test_nothing_qualified_to_tally_exits_2'),
    ("cov", 'skill:readers/scripts/check-reader-output.py', 'TOP_TEXT = ("why_accept", "closest_prior_work", "reuse", "writing_got_in_way", "outside_knowledge")', 'TOP_TEXT = ("why_accept", "closest_prior_work", "reuse", "writing_got_in_way")',
     'test_readers.ReadersTest.test_incomplete_outputs_are_named_and_not_counted'),
    ("cov", 'skill:readers/scripts/check-reader-output.py', 'missing = [p for p in want if p not in seen]', 'missing = []',
     'test_readers.ReadersTest.test_incomplete_outputs_are_named_and_not_counted'),
    ("cov", 'skill:readers/scripts/build-reader-packet.py', 'parts.append(bib.get(k, k))', 'parts.append("cite")',
     'test_readers.ReadersTest.test_the_packet_reads_the_named_sections_keeps_citations_and_records_the_version'),
    ("cov", 'coverage.py', 'if fmt not in check["formats"]:', 'if False:',
     'test_coverage.NeverGreenTest.test_a_format_the_check_cannot_read'),
    ("cov", 'coverage.py', 'missing = [n for n in check["needs"] if K.get(cfg, n) is None]', 'missing = []',
     'test_coverage.NeverGreenTest.test_a_missing_prerequisite'),
    ("cov", 'coverage.py', 'edited = sum(1 for k in o.keys() & c.keys() if o[k] != c[k])', 'edited = 0',
     'test_coverage.StalenessTest.test_an_edited_sentence_in_scope_makes_it_stale_and_one_outside_does_not'),
    ("cov", 'coverage.py', '    if old.get("script") != new["script"]:', '    if False:',
     'test_coverage.StalenessTest.test_a_changed_check_script_makes_it_stale'),
    ("cov", 'coverage.py', '        if (old.get("inputs") or {}).get(role) != new["inputs"].get(role):', '        if False:',
     'test_coverage.StalenessTest.test_a_changed_input_file_makes_it_stale'),
    ("cov", 'coverage.py', '    if rec.get("verdict") == "failed":', '    if False:',
     'test_coverage.NeverGreenTest.test_exit_2_is_a_failure'),
    ("cov", 'coverage.py', '            r = subprocess.run(argv, cwd=tmp, capture_output=True, text=True,\n                               timeout=check.get("timeout") or timeout)', '            r = subprocess.run(argv, cwd=tmp, capture_output=True, text=True)',
     'test_coverage.NeverGreenTest.test_a_timeout_is_a_failure'),
    ("cov", 'coverage.py', '    except (OSError, ValueError):\n        return None, None', '    except (OSError, ValueError):\n        return [], None',
     'test_coverage.NeverGreenTest.test_no_index_means_nothing_is_up_to_date'),
    ("cov", 'coverage.py', '(r["status"] == FAILED and r.get("due"))', 'r["status"] == FAILED',
     'test_coverage.NeverGreenTest.test_a_failed_check_is_rerun_only_when_something_changed'),
    ("cov", 'coverage.py', 'return [r for r in summary["rows"] if r["status"] == NOT_APPLICABLE and not r.get("instead")]', 'return []',
     'test_coverage.NeverGreenTest.test_a_format_the_check_cannot_read'),
    ("cov", 'coverage.py', '    if not bits:\n        return None', '    if False:\n        return None',
     'test_coverage.ShownTest.test_the_reminder_names_what_is_not_current_and_is_silent_otherwise'),
    ("cov", 'coverage.py', '    if missing:\n        return None, "配置的输入在 HEAD 上不存在：', '    if False:\n        return None, "配置的输入在 HEAD 上不存在：',
     'test_coverage.NeverGreenTest.test_an_input_configured_but_absent_at_head_is_a_failure_not_a_pass'),
    ("cov", 'cli.py', '        (Path(ws) / "cache" / "coverage" / "summary.json").unlink(missing_ok=True)', '        pass',
     'test_coverage.UpdateTest.test_a_coverage_failure_during_update_leaves_no_old_summary_standing'),
    ("cov", 'catalogue.py', 'for name in sorted(set(registered) - wired - set(UNWIRED)):', 'for name in []:',
     'test_catalogue.WiringTest.test_the_invariant_sees_an_unwired_check'),
    ("cov", 'catalogue.py', 'for s in sorted(set(skills) - set(installed) - set(SKILLS_NOT_INSTALLED)):', 'for s in []:',
     'test_catalogue.WiringTest.test_the_invariant_sees_a_skill_that_is_not_installed'),
    ("cov", 'catalogue.py', 'for name in sorted(wired - set(registered)):', 'for name in []:',
     'test_catalogue.WiringTest.test_the_invariant_sees_a_catalogued_script_that_is_not_registered'),
    ("cov", 'catalogue.py', 'if len((reason or "").strip()) < UNWIRED_REASON_MIN:', 'if False:',
     'test_catalogue.WiringTest.test_an_unwired_reason_must_say_something'),
    ("cov", 'targets.py', 'if _norm(m.get("venue")) != _norm(venue):', 'if False:',
     'test_coverage.TargetTest.test_wrong_venue_small_corpus_and_missing_files_are_each_named'),
    ("cov", 'targets.py', '" ".join(html.unescape(s or "").split()).casefold()', '" ".join((s or "").split()).casefold()',
     'test_coverage.TargetTest.test_an_escaped_venue_name_matches_and_a_full_corpus_passes'),
    ("cov", 'targets.py', 'elif dt.date.fromisoformat(dm.group(1)) < today:', 'elif False:',
     'test_coverage.TargetTest.test_experiments_without_a_disposition_or_past_review_are_listed'),
    ("cov", 'targets.py', 'if admitted < CORPUS_FLOOR:', 'if False:',
     'test_coverage.TargetTest.test_wrong_venue_small_corpus_and_missing_files_are_each_named'),
    ("cov", 'targets.py', 'gone = [f for f in files if not (d / f).is_file()]', 'gone = []',
     'test_coverage.TargetTest.test_wrong_venue_small_corpus_and_missing_files_are_each_named'),
    ("cov", 'doctor.py', '    for item, msg in TG.doctor_problems(cfg):', '    for item, msg in [("target", p) for p in TG.describe(cfg)["problems"]]:',
     'test_doctor.DoctorTest.test_a_target_that_is_not_registered_is_a_fact_and_a_configured_path_that_does_not_resolve_is_a_problem'),
    ("cov", 'hooks/loop_hook.py', '        line = V.reminder_line(V.load_summary(ws, cfg), ws)', '        line = None',
     'test_hooks.PromptTest.test_the_reminder_carries_the_coverage_line_and_only_when_something_is_not_current'),
    ("cov", 'hooks/loop_hook.py', '        line = f"覆盖：摘要读不出（{type(e).__name__}），不能当作都查过了"', '        line = None',
     'test_hooks.PromptTest.test_the_reminder_carries_the_coverage_line_and_only_when_something_is_not_current'),
    ("B", "inbox.py", "if cand.exists() and cand not in seen:", "if False:",
     "test_inbox.InboxTest.test_a_dropped_folder_becomes_a_workspace_with_its_tex_files"),
    ("B", "inbox.py", 'if h == "Abstract":', 'if False:',
     "test_inbox.InboxTest.test_section_rules_follow_the_headings_with_the_abstract_flat"),
    ("A", "history.py", 's["line"] = text.count("\\n", 0, m.start()) + 1', 's["line"] = 1',
     "test_history.LocateTest.test_sentences_carry_the_file_and_line_where_they_start"),
    ("A", "lintel.py", 'where = " · ".join(x for x in (sec, f"第 {r[\'par\']} 段" if r.get("par") else None, at) if x)', 'where = sec',
     "test_lintel.LocateRowsTest.test_rows_carry_where_copy_and_both_texts"),
    ("1.1", "doctor.py", 'for key in ("evidence_dir", "keymap_from"):', "for key in ():",
     "test_doctor.DoctorTest.test_each_wrong_path_is_named"),
    ("1.1", "cli.py", 'print(f"doctor: {len(problems)} 项读不到或不存在")\n        return 1', 'print(f"doctor: {len(problems)} 项读不到或不存在")\n        return 0',
     "test_doctor.DoctorTest.test_cli_exit_code"),
    ("1.1", "doctor.py", "if not hits and history:", "if not hits and history and False:",
     "test_doctor.DoctorTest.test_a_rebound_workspace_whose_history_is_elsewhere_is_not_a_fault"),
    ("1.1", "doctor.py", "        elif not hits:\n            bad(", "        elif False:\n            bad(",
     "test_doctor.DoctorTest.test_a_rebound_workspace_whose_history_is_elsewhere_is_not_a_fault"),
    ("F3", "gitio.py", "    b = _batches.get(str(repo))\n    if b is None:", "    b = None\n    if b is None:",
     "test_gitio.BatchTest.test_inside_a_batch_reading_objects_starts_no_process"),
    ("F3", "gitio.py", '        return got[0] if got else None', '        return got[0] if got and got[1] == "blob" else None',
     "test_gitio.BatchTest.test_batch_answers_exactly_what_single_calls_answer"),
    ("F3", "gitio.py", "        _batches.pop(key, None)  # already gone if it broke mid-block", "        del _batches[key]",
     "test_gitio.BatchTest.test_a_batch_that_dies_falls_back_to_single_calls"),
    ("F3", "index.py", 'with gitio.batch(cfg["repo"]):', "if True:",
     "test_index.IndexTest.test_building_the_index_reads_blobs_without_a_process_each"),
    ("1.2", "history.py", "aligner = aligner or A.align", "aligner = aligner or positional_aligner",
     "test_history.StableIdTest.test_moved_paragraph_keeps_ids"),
    ("1.2", "align.py", "if R >= JOIN_MIN and R >= single + JOIN_GAIN:", "if False:",
     "test_history.StableIdTest.test_split_and_merge_are_recognised"),
    ("1.2", "align.py", "if best and best[0] >= DERIVED_COVER:\n            derived.append", "if False:\n            derived.append",
     "test_history.StableIdTest.test_reused_text_across_a_gap_is_not_called_new"),
    ("1.2", "align.py", "need = min(MIN_RUN, len(pw))", "need = 1",
     "test_history.StableIdTest.test_scattered_common_words_are_not_reuse"),
    ("1.5", "transcripts.py", 'if att and att.get("type") == "queued_command"', 'if False and att and att.get("type") == "queued_command"',
     "test_transcripts.TranscriptReadTest.test_prompt_and_queued_messages_are_both_read"),
    ("1.5", "transcripts.py", 'key = (r["timestamp"], text)', 'key = (r["timestamp"], text, r.get("sessionId"))',
     "test_transcripts.TranscriptReadTest.test_copies_in_continued_sessions_count_once"),
    ("1.5", "transcripts.py", 'text = _REMINDER.sub("", raw).strip()', 'text = raw.strip()',
     "test_transcripts.TranscriptReadTest.test_injected_reminder_is_removed_and_counted"),
    ("1.5", "transcripts.py", 'k = f"origin:{kind}" if kind else _unclassified_kind(raw)\n                    uncl[k] = uncl.get(k, 0) + 1', 'pass',
     "test_transcripts.TranscriptReadTest.test_non_author_records_are_counted_not_dropped"),
    ("1.3", "changesets.py", "entering_or_leaving = sorted(w for w in shared if (w in df_prev) != (w in df_cur))", "entering_or_leaving = sorted(shared)",
     "test_changesets.TriggerTest.test_unrelated_message_is_not_a_trigger"),
    ("1.3", "changesets.py", "elif len(rare) >= MIN_SHARED_RARE:", "elif len(shared) >= MIN_SHARED_RARE:",
     "test_changesets.TriggerTest.test_unrelated_message_is_not_a_trigger"),
    ("1.3", "changesets.py", "    return words - STOP - PROCESS_WORDS", "    return words - STOP",
     "test_changesets.TriggerTest.test_unrelated_message_is_not_a_trigger"),
    ("1.3", "changesets.py", "if len(mids) > 1 or (mids and unknown):", "if len(mids) > 1:",
     "test_changesets.TriggerTest.test_mixed_commit_is_marked"),
    ("1.3", "changesets.py", "                if mid in known:", "                if True:",
     "test_changesets.TriggerTest.test_commit_trailer_must_point_to_a_real_message"),
    ("1.3", "changesets.py", "if entering_or_leaving:", "if False:",
     "test_changesets.TriggerTest.test_entering_word_attributes_the_row"),
    ("1.5", "threads.py", "if q in sn or (len(sn) >= 20 and sn in q):", "if False:",
     "test_threads.AttachTest.test_quoted_fragment_attaches"),
    ("1.5", "threads.py", 'if s and s["sid"] not in seen:', "if False:",
     "test_threads.AttachTest.test_label_attaches"),
    ("1.5", "threads.py", 'if v["time"] <= t:', "if True:",
     "test_threads.AttachTest.test_message_before_first_version_has_no_version"),
    ("1.5", "threads.py", 'if s and s["sid"] not in seen:', 'if s is None or s["sid"] not in seen:',
     "test_threads.AttachTest.test_label_that_does_not_exist_is_not_attached"),
    ("1.4", "checks.py", '        return {**out, "status": "not_found", "source_blob": blob}', '        return {**out, "status": "found", "source_blob": blob}',
     "test_checks.CheckTest.test_fabricated_span_is_not_found_and_only_its_sentence_changes"),
    ("1.4", "checks.py", 'json.dumps([norm(s["text"]), entries, blobs, maps_sig,', 'json.dumps([norm(s["text"]), blobs, maps_sig,',
     "test_checks.CheckTest.test_ledger_change_invalidates_the_cached_sentence"),
    ("1.4", "checks.py", "        if sig in cache:", "        if False:",
     "test_checks.CheckTest.test_only_changed_sentences_are_rechecked"),
    ("1.4", "checks.py", "            if weak_only[k] and False in dags:", "            if False:",
     "test_checks.CheckTest.test_dagger_and_missing_entries_are_reported"),
    ("1.4", "checks.py", "        if i < 0:\n            unattached.append(e)", "        if i < 0:\n            pass",
     "test_checks.CheckTest.test_missing_source_file_and_unattached_entry"),
    ("1.6", "index.py", '        elif p.read_bytes() != fresh[name]:', '        elif False:',
     "test_index.IndexTest.test_tampered_index_is_named_as_tampered"),
    ("1.6", "index.py", 'if (old.get("head"), old.get("transcripts")) != (new["head"], new["transcripts"]):', 'if False:',
     "test_index.IndexTest.test_new_commit_is_named_as_stale"),
    ("1.6", "index.py", 'chk = {k: v for k, v in chk.items() if k not in ("evaluated", "reused")}', 'chk = dict(chk)',
     "test_index.IndexTest.test_warm_and_cold_cache_give_the_same_bytes"),
    ("1.6", "index.py", '        if not p.exists():\n            diffs.append((name, "缺失"))', '        if not p.exists():\n            continue',
     "test_index.IndexTest.test_missing_index_file_is_reported"),
    ('4.2', 'lintel.py', 'if "status" in body:', 'if False:',
     'test_lintel.SyncTest.test_unchanged_content_is_not_rewritten'),
    ('4.2', 'lintel.py', '        same = old is not None and content_hash(old) == content_hash(a)', '        same = False',
     'test_lintel.SyncTest.test_unchanged_content_is_not_rewritten'),
    ('live', 'lintel.py', 'key, when = f"change:{lc[\'id\']}:traced", when_lc', 'key, when = f"change:{lc[\'id\']}:traced:{label}", when_lc',
     'test_lintel.IdentityTest.test_the_panel_and_a_late_label_do_not_make_it_new'),
    ('live', 'lintel.py', 'key, when = f"none:{ws}", None', 'key, when = f"none:{ws}:{summary[\'head\']}", None',
     'test_lintel.IdentityTest.test_no_change_yet_stays_the_same_thing_across_commits'),
    ('live', 'lintel.py', '    body["events"] = [{k: v for k, v in e.items() if k != "at"} for e in body.get("events", [])]', '    body.pop("events", None)',
     'test_lintel.SyncTest.test_an_event_alone_is_written'),
    ('live', 'lintel.py', '    body = {k: v for k, v in a.items() if k not in VOLATILE}', '    body = {k: v for k, v in a.items() if k not in VOLATILE and k != "detail"}',
     'test_lintel.SyncTest.test_a_panel_change_is_written_though_the_thing_is_the_same'),
    ('live', 'lintel.py', 'rank = "event" if now - when_lc < DRIFT_FRESH else "none"', 'rank = "event"',
     'test_lintel.OneActivityTest.test_an_untraced_change_is_time_sensitive'),
    ('live', 'lintel.py', '"activityAt": _iso(when) if when is not None else None,', '"activityAt": _iso(now),',
     'test_lintel.IdentityTest.test_the_time_is_when_it_happened'),
    ("4.2", "lintel.py", "stale = not p.exists() or now - p.stat().st_mtime > heartbeat / 2",
     "stale = not p.exists()", "test_lintel.SyncTest.test_heartbeat_rewrites_the_same_bytes_so_seen_is_not_reset"),
    ("4.2", "lintel.py", "        if p.name not in keep and p.stem in LEGACY_IDS:", "        if False:",
     "test_lintel.SyncTest.test_a_card_from_the_old_six_card_producer_is_removed_but_another_manuscript_is_not"),
    ("4.2", "lintel.py", "        if p.name not in keep and p.stem in LEGACY_IDS:", "        if p.name not in keep:",
     "test_lintel.SyncTest.test_a_card_from_the_old_six_card_producer_is_removed_but_another_manuscript_is_not"),
    ("4.2", "lintel.py", '    elif lc and not lc["traced"]:', "    elif False:",
     "test_lintel.OneActivityTest.test_an_untraced_change_is_time_sensitive"),
    ("4.2", "lintel.py", 'label = _fit(lc["label"], LABEL_MAX) if lc.get("label") else "改了"', 'label = lc["label"] if lc.get("label") else "改了"',
     "test_lintel.OneActivityTest.test_the_wing_is_the_reason_claude_wrote_else_the_count"),
    ("4.2", "lintel.py", '    if problems:\n        text = "；".join(problems)[:20000]\n        label, tone, center, rank, flagged = "跑挂了"',
     '    if False:\n        text = "；".join(problems)[:20000]\n        label, tone, center, rank, flagged = "跑挂了"',
     "test_lintel.OneActivityTest.test_a_fault_outranks_a_change"),
    ("4.2", "lintel.py", '    return [a]', '    return [a, dict(a, id="draft")]',
     "test_lintel.OneActivityTest.test_one_activity_whatever_the_state"),
    ("4.2", "lintel.py", '    a = _prune(a)', '    a = a',
     "test_lintel.OneActivityTest.test_no_none_reaches_the_host"),
    ("4.2", "index.py", '    triggers = [t for t in c.get("triggers", ()) if isinstance(t, str) and t.startswith("h-")]',
     '    triggers = [t for t in c.get("triggers", ()) if isinstance(t, str)] or ["h-guess"]',
     "test_lintel.SummaryViewTest.test_untraced_changeset_guesses_nothing"),
    ("2.3", "explain.py", 'KEYS = {"读成": "reading", "改了": "changed", "依据": "basis", "标签": "label"}',
     'KEYS = {"读成": "reading", "改了": "changed", "依据": "basis"}',
     "test_explain.ParseTest.test_the_label_line_is_the_notch_wing_and_stays_short_in_the_record"),
    ("v2-D5", "lintel.py", "    if not registered(home, producer):\n        raise NotRegistered", "    if False:\n        raise NotRegistered",
     "test_lintel.OffByDefaultTest.test_unregistered_producer_writes_nothing_and_creates_no_directory"),
    ("v2-D5", "lintel.py", "return isinstance(producers, dict) and producer in producers", "return producer in (producers or ())",
     "test_lintel.OffByDefaultTest.test_malformed_registry_counts_as_unregistered"),
    ("v2-D5", "cli.py", "            print(e, file=sys.stderr)\n            return 2", "            print(e, file=sys.stderr)\n            return 0",
     "test_lintel.CliOffByDefaultTest.test_cli_refuses_with_exit_2_and_creates_nothing"),
    ('2.3', 'explain.py', '    if out["reading"] is None:\n        w = willow_reading(text)', '    if False:\n        w = willow_reading(text)',
     'test_explain.ParseTest.test_first_line_reading_counts_when_the_block_omits_it'),
    ('2.3', 'explain.py', 'if f and out[KEYS[f.group(1)]] is None and f.group(2):', 'if f and f.group(2):',
     'test_explain.ParseTest.test_first_occurrence_of_a_field_wins_and_empty_values_do_not_count'),
    ('2.3', 'explain.py', ' and a["session"] in h["sessions"]]', ']',
     'test_explain.BuildTest.test_replies_from_another_session_are_not_borrowed'),
    ('2.3', 'explain.py', 'out["over_limit"] = len(lines) > MAX_LINES', 'out["over_limit"] = False',
     'test_explain.ParseTest.test_more_than_six_lines_is_flagged_not_dropped'),
    ('2.4', 'health.py', 'if err and not err.get("cleared_at"):', 'if err:',
     'test_health.UpdateTest.test_a_failure_is_recorded_and_stays_visible_until_a_later_success'),
    ('2.4', 'health.py', '    if src.get("head") != head:', '    if False:',
     'test_health.HealthTest.test_a_new_commit_without_an_update_is_lag'),
    ('2.4', 'health.py', '    if src.get("transcripts") != now_files:', '    if False:',
     'test_health.HealthTest.test_a_grown_transcript_is_lag'),
    ('2.4', 'health.py', '    if not h.get("last_ok"):', '    if False:',
     'test_health.HealthTest.test_never_updated_is_a_problem_not_silence'),
    ('2.4', 'cli.py', '            dirty.touch()\n', '            pass\n',
     'test_health.UpdateTest.test_a_running_update_is_not_doubled_but_asked_to_go_round_again'),
    ('2.4', 'cli.py', 'if time.time() - lock.stat().st_mtime <= STALE_LOCK:', 'if True:',
     'test_health.UpdateTest.test_a_lock_left_by_a_killed_update_is_taken_over'),
    ('2.4', 'cli.py', '                    HL.record_error(ws, f"{type(e).__name__}：{e}")\n                    print(f"update 失败', '                    print(f"update 失败',
     'test_health.UpdateTest.test_a_failure_is_recorded_and_stays_visible_until_a_later_success'),
    ('live', 'changesets.py', '            elif session_mid:\n', '            elif False:\n',
     'test_changesets.SessionCommitTest.test_a_quiet_commit_the_session_made_is_traced_to_the_authors_latest_message_there'),
    ('live', 'changesets.py', '        session_mid = said[-1]["mid"] if said else None', '        session_mid = said[0]["mid"] if said else None',
     'test_changesets.SessionCommitTest.test_a_quiet_commit_the_session_made_is_traced_to_the_authors_latest_message_there'),
    ('live', 'transcripts.py', '                    if t0 is None or not GIT_COMMIT.search(cmd):\n', '                    if t0 is None:\n',
     'test_changesets.SessionCommitTest.test_a_commit_line_in_git_log_output_is_not_the_session_committing'),
    ('live', 'transcripts.py', '                    if not (repo_path and (any(n and n in cmd for n in repo_names) or _under(cwd, repo_path))):\n', '                    if False:\n',
     'test_changesets.SessionCommitTest.test_a_commit_call_that_does_not_name_the_manuscripts_repository_is_not_this_commit'),
    ('live', 'changesets.py', 'c["t0"] - CALL_SLACK <= cur["time"] <= c["t1"] + CALL_SLACK', 'True',
     'test_changesets.SessionCommitTest.test_a_commit_call_at_another_time_is_not_this_commit'),
    ('2.1', 'hooks/loop_hook.py', '    prompt = payload.get("prompt")', '    prompt = payload.get("user_prompt")',
     'test_hooks.PromptTest.test_prompt_is_kept_verbatim_and_the_block_is_asked_for'),
    ("live", 'hooks/loop_hook.py', 'from loop import health as HL  # noqa: E402\n', 'from loop import health as HL  # noqa: E402\nfrom loop import lintel as LN  # noqa: E402\n',
     'test_hooks.BrokenNotchModuleTest.test_the_guard_still_refuses_a_write_into_human'),
    ("live", 'hooks/loop_hook.py', '    except Exception as e:  # noqa: BLE001 -- the notch is optional; the guard and the reminder are not\n        HL.record_event(ws, "hook_error", f"刘海模块读不进来：{type(e).__name__}：{e}")\n        return False',
     '    except ImportError:\n        raise',
     'test_hooks.BrokenNotchModuleTest.test_a_prompt_still_gets_the_reminder_and_the_failure_is_recorded'),
    ("live", 'cli.py', '    n = sub.add_parser("lintel", help="write activities for the lintel notch host")', '    from . import lintel as _LN\n    n = sub.add_parser("lintel", help="write activities for the lintel notch host")',
     'test_hooks.BrokenNotchModuleTest.test_the_command_line_still_starts'),
    ('2.1', 'hooks/loop_hook.py', '    if not isinstance(prompt, str):\n        HL.record_event(', '    if not isinstance(prompt, str):\n        return None\n        HL.record_event(',
     'test_hooks.PromptTest.test_the_documentations_field_name_is_a_visible_error_not_silence'),
    ('2.1', 'hooks/loop_hook.py', '        if br == cfg["transcripts"]["git_branch"]:', '        if True:',
     'test_hooks.PromptTest.test_another_branch_or_directory_is_not_recorded'),
    ('2.1', 'hooks/loop_hook.py', '    elif tool == "Bash" and GIT_RE.search(', '    elif False and GIT_RE.search(',
     'test_hooks.TriggerTest.test_draft_and_ledger_writes_and_git_commands_ask_for_an_update'),
    ('2.1', 'hooks/loop_hook.py', '            if _is_draft(rel, cfg["draft"]["glob"]) or', '            if False or',
     'test_hooks.TriggerTest.test_draft_and_ledger_writes_and_git_commands_ask_for_an_update'),
    ('2.2', 'hooks/loop_hook.py', '            if t and _under(t, human):', '            if False:',
     'test_hooks.GuardTest.test_absolute_and_relative_writes_into_human_are_refused_and_recorded'),
    ('2.2', 'hooks/loop_hook.py', 'if _command_name(words[0]) not in READ_ONLY or writes_human:', 'if writes_human:',
     'test_hooks.GuardTest.test_shell_writes_naming_human_are_refused_including_the_home_form'),
    ('2.2', 'hooks/loop_hook.py', 'writes_human = any(', 'writes_human = False and any(',
     'test_hooks.GuardTest.test_reading_human_is_allowed_but_redirecting_into_it_is_not'),
    ('2.2', 'hooks/loop_hook.py', '        if not touched:\n            continue\n', '',
     'test_hooks.GuardTest.test_reading_human_is_allowed_but_redirecting_into_it_is_not'),
    ('quote', 'hooks/loop_hook.py', '    if q:\n        return SEGMENTS.split(cmd)', '    if True:\n        return SEGMENTS.split(cmd)',
     'test_hooks.GuardTest.test_a_read_is_split_and_named_the_way_the_shell_does_it'),
    ('quote', 'hooks/loop_hook.py', '    return base if d in SYSTEM_BIN else _unquote(word)', '    return _unquote(word)',
     'test_hooks.GuardTest.test_a_read_is_split_and_named_the_way_the_shell_does_it'),
    ('quote', 'hooks/loop_hook.py', 'if ">" in w and set(w) <= OPERATOR]', 'if ">" in w]',
     'test_hooks.GuardTest.test_a_read_is_split_and_named_the_way_the_shell_does_it'),
    ('quote', 'hooks/loop_hook.py', '    return base if d in SYSTEM_BIN else _unquote(word)', '    return base',
     'test_hooks.GuardTest.test_quotes_do_not_hide_a_write'),
    ('quote', 'hooks/loop_hook.py', 'if not words or SUBSTITUTION.search(seg):', 'if not words:',
     'test_hooks.GuardTest.test_quotes_do_not_hide_a_write'),
    ('quote', 'hooks/loop_hook.py', '(c == "&" and cmd[i - 1:i] not in (">", "<") and cmd[i + 1:i + 2] != ">")', 'False',
     'test_hooks.GuardTest.test_quotes_do_not_hide_a_write'),
    ('quote', 'hooks/loop_hook.py', '    return [_unquote(words[i + 1]) for i, w', '    return [words[i + 1] for i, w',
     'test_hooks.GuardTest.test_quotes_do_not_hide_a_write'),
    ('2.1', 'hooks/loop_hook.py', '    return rel in glob if isinstance(glob, list) else fnmatch.fnmatch(rel, glob)', '    return fnmatch.fnmatch(rel, glob)',
     'test_hooks.TriggerTest.test_a_draft_made_of_several_files_is_matched_file_by_file'),
    ('envelope', 'hooks/loop_hook.py', 'r"bash-input|bash-stdout|bash-stderr|"', 'r""',
     'test_hooks.PromptTest.test_a_shell_command_run_with_bang_is_not_recorded_as_the_authors_words'),
    ('envelope', 'transcripts.py', '                    if raw.lstrip().startswith("<bash-input>"):', '                    if False:',
     'test_transcripts.TranscriptReadTest.test_a_shell_command_run_with_bang_is_not_an_authors_message'),
    ('envelope', 'hooks/loop_hook.py', '    if ENVELOPE.match(prompt):\n', '    if False:\n',
     'test_hooks.PromptTest.test_system_envelopes_are_not_recorded_as_the_authors_words'),
    ('envelope', 'hooks/loop_hook.py', '        return reminder  # the turn it starts can still edit the draft', '        return None',
     'test_hooks.PromptTest.test_system_envelopes_are_not_recorded_as_the_authors_words'),
    ('2.2', 'hooks/loop_hook.py', '    p = os.path.expanduser(tok)', '    p = tok',
     'test_hooks.GuardTest.test_shell_writes_naming_human_are_refused_including_the_home_form'),
    ('2.2', 'hooks/loop_hook.py', '    path, root = _real(path), _real(root)', '    path, root = str(path), str(root)',
     'test_hooks.GuardTest.test_shell_writes_naming_human_are_refused_including_the_home_form'),
    ('2.5', 'index.py', 'json.dumps([salt, old, new, old_groups, new_groups]', 'json.dumps([salt, old, old_groups, new_groups]',
     'test_index.DiskCacheTest.test_a_rewritten_commit_does_not_reuse_the_old_alignment'),
    ('2.5', 'index.py', '            return json.loads(p.read_text(encoding="utf-8"))\n        except (OSError, ValueError):', '            return json.loads(p.read_text(encoding="utf-8"))\n        except OSError:',
     'test_index.DiskCacheTest.test_unreadable_cache_files_are_recomputed_not_trusted'),
    ('2.5', 'transcripts.py', 'known == [st.st_size, st.st_mtime_ns, False]', 'known[2] is False',
     'test_index.DiskCacheTest.test_a_session_file_that_gains_the_branch_is_read_again'),
    ('fix1', 'health.py', 'if e.get("kind") == kind and e.get("t", 0) > since]', 'if e.get("kind") == kind]',
     'test_health.AckTest.test_ack_clears_what_was_shown_but_keeps_the_record'),
    ('fix1', 'health.py', '    bad = _unacked(h, "hook_error")\n', '    bad = _unacked(h, "hook_error") + _unacked(h, "guard_denied")\n',
     'test_hooks.GuardTest.test_absolute_and_relative_writes_into_human_are_refused_and_recorded'),
    ('fix1', 'lintel.py', '{"label": "拦下", "value": str(len(notices))', '{"label": "拦下", "value": "0"',
     'test_lintel.OneActivityTest.test_passive_things_stay_off_the_wings'),
    ('fix2', 'cli.py', '                if a.rebuild:\n', '                if True:\n',
     'test_lintel.ResidentTest.test_the_resident_producer_reads_the_index_and_does_not_rebuild_it'),
    ('fix2', 'cli.py', '    return "loop" in r.stdout and "lintel" in r.stdout', '    return True',
     'test_lintel.ResidentTest.test_a_pid_that_is_not_a_producer_does_not_count_as_one'),
    ('fix2', 'hooks/loop_hook.py', '    if LN.registered(LN.lintel_home(), LN.PRODUCER) and not', '    if not',
     'test_hooks.ProducerTest.test_the_resident_producer_is_started_only_when_lintel_registered_it'),
    ('latex', 'text.py', '    tex = _TEX_COMMENT.sub("", tex)\n', '',
     'test_latex.LatexTest.test_sections_and_comments'),
    ('latex', 'text.py', '_TEX_COMMENT = re.compile(r"(?<!\\\\)%.*$", re.M)', '_TEX_COMMENT = re.compile(r"%.*$", re.M)',
     'test_latex.LatexTest.test_only_the_chosen_sections_become_sentences'),
    ('latex', 'history.py', 'md = "\\n\\n".join(t for _, t in texts)', 'md = gitio.show(repo, c["sha"], paths[0])',
     'test_latex.MultiFileTest.test_a_commit_to_either_file_is_a_new_version_of_one_draft'),
    ('latex', 'history.py', '    return list(g) if isinstance(g, list) else [f":(glob){g}"]', '    return [f":(glob){g}"]',
     'test_latex.MultiFileTest.test_a_commit_to_either_file_is_a_new_version_of_one_draft'),
    ('rebind', 'explain.py', '        if not line.strip() or WILLOW_STOP.match(line):', '        if WILLOW_STOP.match(line):',
     'test_explain.ParseTest.test_a_reading_written_over_several_lines_is_read_to_its_end'),
    ('rebind', 'explain.py', '        if cur is None or h.get("channel", "prompt") != "queued":', '        if True:',
     'test_explain.BuildTest.test_a_message_typed_mid_turn_does_not_take_the_turns_block'),
    ('rebind', 'transcripts.py', ' + [(s["git_branch"], str(s["cwd_prefix"])) for s in t.get("also", [])]', '',
     'test_hooks.AlsoSourceTest.test_an_also_source_is_read_but_the_hooks_do_not_act_on_it'),
    # 总览（lintel 分镜 ㊸–㊽，作者 09-21）
    ('overview', 'overview.py', 'if cur and v["time"] - cur[-1]["time"] >= gap_days * 86400:', 'if False:',
     'test_overview.StagesTest.test_a_gap_of_three_days_or_more_starts_a_stage'),
    ('overview', 'overview.py', '            if len(empty) >= gap_days:', '            if False:',
     'test_overview.StagesTest.test_a_long_empty_run_folds_into_one_gap_bar'),
    ('overview', 'overview.py', '    if not cur or action not in cur["actions"]:', '    if not cur:',
     'test_overview.AlignmentTest.test_an_action_the_panel_did_not_offer_writes_nothing'),
    ('overview', 'overview.py', '            args += ["--credits", str(cpath)]', '            pass',
     'test_overview.AlignmentTest.test_marking_a_method_credit_takes_the_sentence_out_of_missing'),
    ('overview', 'overview.py', 'cells.append({"title": "稿件仓 issue", "text": "取不到", "value": "取不到", "sub": "gh 没登录或断网，不写数"})',
     'cells.append({"title": "稿件仓 issue", "text": "已关 0 / 共 0", "sub": ""})',
     'test_overview.TodoTest.test_issues_that_cannot_be_asked_say_so_instead_of_zero'),
    ('overview', 'inbox.py', '        if _kind(p) == "action":\n            continue', '        if False:\n            continue',
     'test_overview.InboxActionTest.test_loop_inbox_does_not_refuse_an_action_as_a_bad_drop'),
    ('overview', 'inbox.py', 'if not isinstance(d, dict) or d.get("kind") != "action" or d.get("activity") != activity:',
     'if not isinstance(d, dict) or d.get("kind") != "action":',
     'test_overview.InboxActionTest.test_actions_for_another_manuscript_are_left_alone'),
    ('overview', 'lintel.py', '"rows": _rows(h, names) or None, "sections": secs([h["id"]])}', '"rows": _rows(h, names) or None}',
     'test_overview.PanelTest.test_overview_rides_on_the_detail_and_history_rows_name_their_sections'),
    # 改句的门（spec 2026-09-22）：工作区检查、收尾判定、钩子注入与拦截，各拿掉一处。
    ("gates", 'coverage.py', '    todo = [("工作区", s) for s in r["unresolved"]] + [("回复", s) for s in chat]', '    todo = []',
     'test_coverage.RealCheckTest.test_an_uncommitted_rewrite_is_read_and_holds_the_turn_until_fixed_or_accepted'),
    ("gates", 'coverage.py', 'if cached and cached.get("fingerprint") == fp and cached.get("head") == head',
     'if cached and cached.get("head") == head',
     'test_coverage.RealCheckTest.test_an_uncommitted_rewrite_is_read_and_holds_the_turn_until_fixed_or_accepted'),
    ("gates", 'hooks/loop_hook.py', '    if r.get("cached") or not r.get("unresolved"):\n        return None', '    return None',
     'test_hooks.RewriteGateTest.test_a_script_write_is_read_after_the_tool_and_only_once'),
    ("gates", 'hooks/loop_hook.py', '    return {"decision": "block", "reason": reason}', '    return None',
     'test_hooks.RewriteGateTest.test_the_stop_is_blocked_once_then_the_override_is_recorded'),
    # lintel C4–C6 (design 2026-09-22-awt-live B3): start, running, landing, the seen capsule, and the turn they read
    ("turns", 'lintel.py', 'START_FRESH = 45.0', 'START_FRESH = 0.0',
     'test_lintel.TurnStateTest.test_every_message_starts_with_a_two_line_card'),
    ("turns", 'lintel.py', 'and (not is_running or (start and when_lc >= start)))', 'and True)',
     'test_lintel.TurnStateTest.test_an_old_drift_does_not_beat_running_but_a_drift_in_this_turn_does'),
    ("turns", 'lintel.py', 'caught_up = ended is not None and built_at is not None and built_at >= ended', 'caught_up = ended is not None',
     'test_lintel.TurnStateTest.test_landing_pops_two_lines_once_the_index_has_caught_up'),
    ("turns", 'lintel.py', '        a["pillSeen"] = {"pulse": False, "agoSince": _iso(when)}', '        pass',
     'test_lintel.TurnStateTest.test_after_it_is_seen_the_capsule_keeps_the_bracket_and_how_long_ago'),
    ("turns", 'lintel.py', '"labelUntilSeen": not run_state,', '"labelUntilSeen": True,',
     'test_lintel.TurnStateTest.test_running_names_the_action_ticks_from_the_first_touch_and_does_not_pop'),
    ("turns", 'lintel.py', '                          and now - ended < LANDED_HOLD)', '                          )',
     'test_lintel.TurnStateTest.test_a_turn_that_only_ran_the_readers_lands_with_the_weakest_item'),
    ("turns", 'index.py', 'strength = "sentence" if srcs & {"提交信息", "脚本推断"} else ("session" if "提交时的会话" in srcs else None)',
     'strength = "session" if srcs else None', 'test_lintel.SummaryViewTest.test_how_firmly_it_was_traced_is_carried_to_the_notch'),
    ("turns", 'turns.py', '            ended = None      # a touch after a stop', '            pass      # a touch after a stop',
     'test_turns.TurnTest.test_a_touch_after_a_stop_means_that_stop_was_blocked'),
    ("turns", 'turns.py', '            if r["t"] >= p["t"] + PREVIOUS_STOP:', '            if True:',
     'test_turns.TurnTest.test_the_previous_turns_stop_in_the_same_second_does_not_end_this_one'),
    ("turns", 'turns.py', '    if reason.startswith("head:"):', '    if reason.startswith("head:") or reason == "git":',
     'test_turns.TurnTest.test_a_turn_that_touched_nothing_is_not_running'),
    ("turns", 'cli.py', "                        TN.record(ws, f\"head:{summary['head']}\")", '                        pass',
     'test_turns.UpdateRecordsTest.test_update_records_its_reason_and_a_new_manuscript_head'),
]


def _run_test(engine_dir, test, extra_paths=(), env_extra=None):
    # AWT_LOOP_ENGINE tells out-of-tree tests (they locate the engine themselves) to use this copy,
    # otherwise they would import the unmutated engine and never go red.
    paths = [str(engine_dir), str(engine_dir / "tests"), *map(str, extra_paths)]
    env = dict(os.environ, PYTHONPATH=os.pathsep.join(paths), AWT_LOOP_ENGINE=str(engine_dir))
    # the copy has no repository root around it; the overview runs the toolkit's claim-ledger audit from the real one
    env.setdefault("LOOP_CLAIM_AUDIT", str(ENGINE.parents[2] / ".claude/skills/audit/scripts/audit-claim-ledger.py"))
    env.setdefault("AWT_ROOT", str(ENGINE.parents[2]))  # the catalogue's scripts and registries are in the real checkout
    env.update(env_extra or {})
    r = subprocess.run([sys.executable, "-m", "unittest", test], cwd=engine_dir / "tests", env=env, capture_output=True)
    return r.returncode == 0


def run(step=None, mutations=None, extra_paths=()):
    mutations = MUTATIONS if mutations is None else mutations
    bad = 0
    baseline = {}
    ignore = shutil.ignore_patterns("__pycache__", ".*")
    with tempfile.TemporaryDirectory() as b:
        # Baselines run in an unmutated copy laid out exactly like the mutated ones: a test that cannot even
        # run in a copy would otherwise "go red" for every mutation.
        base = Path(b) / "writing-loop"
        shutil.copytree(ROOT, base, ignore=ignore)
        for st, fname, old, new, test in mutations:
            if step and st != step:
                continue
            if test not in baseline:
                baseline[test] = _run_test(base / "engine", test, extra_paths)
            if not baseline[test]:
                print(f"[{st}] 基线就不通过  {test}（未注入故障时已失败，变红不说明任何事）")
                bad += 1
                continue
            bad += _mutate_and_run(st, fname, old, new, test, extra_paths, ignore)
    print(f"redcheck: {bad} 个变异没有被测试看见" if bad else "redcheck: 每个变异都让对应测试变红")
    return 1 if bad else 0


def _mutate_and_run(st, fname, old, new, test, extra_paths, ignore):
    with tempfile.TemporaryDirectory() as t:
        root = Path(t) / "writing-loop"
        shutil.copytree(ROOT, root, ignore=ignore)
        dst = root / "engine"
        env_extra = {}
        if fname.startswith("skill:"):
            # A skill's script lives outside writing-loop/: copy that skill, mutate the copy, point its tests at it.
            skill, _, rel = fname[len("skill:"):].partition("/")
            sk = Path(t) / "skill" / skill
            shutil.copytree(ENGINE.parents[2] / ".claude" / "skills" / skill, sk, ignore=ignore)
            f = sk / rel
            env_extra[f"AWT_{skill.upper()}_DIR"] = str(sk / "scripts")
        else:
            f = (root / fname) if "/" in fname else (dst / "loop" / fname)
        src = f.read_text(encoding="utf-8")
        if src.count(old) != 1:
            print(f"[{st}] {fname}: 变异锚点出现 {src.count(old)} 次（应为 1），无法注入")
            return 1
        f.write_text(src.replace(old, new), encoding="utf-8")
        red = not _run_test(dst, test, extra_paths, env_extra)
        print(f"[{st}] {'变红' if red else '没变红'}  {test}  ← {fname}: {old[:50]!r}")
        return 0 if red else 1


if __name__ == "__main__":
    sys.exit(run(sys.argv[1] if len(sys.argv) > 1 else None))
